# --- buildspec.yml (root) ---
version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: "coworking-analytics-fay"
    IMAGE_TAG: "latest"
phases:
  pre_build:
    commands:
      - echo "== Pre-build =="
      - ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo "Login to ECR: $IMAGE_URI"
      - aws ecr get-login-password | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - SHORT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7 || echo "local")
      - BUILD_DATE=$(date +%Y%m%d)
  build:
    commands:
      - echo "== Build Docker image =="
      - docker build -t $IMAGE_URI:$IMAGE_TAG -t $IMAGE_URI:$BUILD_DATE-$SHORT_SHA .
  post_build:
    commands:
      - echo "== Push to ECR =="
      - docker push $IMAGE_URI:$IMAGE_TAG
      - docker push $IMAGE_URI:$BUILD_DATE-$SHORT_SHA
      - printf '{"imageUri":"%s"}' "$IMAGE_URI:$BUILD_DATE-$SHORT_SHA" > imageDetail.json
artifacts:
  files:
    - imageDetail.json
